/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalasRouteImport } from './routes/salas'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalasSalaIdRouteImport } from './routes/salas_.$salaId'
import { Route as GestaoPainelRouteImport } from './routes/gestao_.painel'

const SalasRoute = SalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalasSalaIdRoute = SalasSalaIdRouteImport.update({
  id: '/salas_/$salaId',
  path: '/salas/$salaId',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoPainelRoute = GestaoPainelRouteImport.update({
  id: '/gestao_/painel',
  path: '/gestao/painel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gestao': typeof GestaoRoute
  '/salas': typeof SalasRoute
  '/gestao/painel': typeof GestaoPainelRoute
  '/salas/$salaId': typeof SalasSalaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gestao': typeof GestaoRoute
  '/salas': typeof SalasRoute
  '/gestao/painel': typeof GestaoPainelRoute
  '/salas/$salaId': typeof SalasSalaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gestao': typeof GestaoRoute
  '/salas': typeof SalasRoute
  '/gestao_/painel': typeof GestaoPainelRoute
  '/salas_/$salaId': typeof SalasSalaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gestao' | '/salas' | '/gestao/painel' | '/salas/$salaId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gestao' | '/salas' | '/gestao/painel' | '/salas/$salaId'
  id:
    | '__root__'
    | '/'
    | '/gestao'
    | '/salas'
    | '/gestao_/painel'
    | '/salas_/$salaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestaoRoute: typeof GestaoRoute
  SalasRoute: typeof SalasRoute
  GestaoPainelRoute: typeof GestaoPainelRoute
  SalasSalaIdRoute: typeof SalasSalaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salas': {
      id: '/salas'
      path: '/salas'
      fullPath: '/salas'
      preLoaderRoute: typeof SalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salas_/$salaId': {
      id: '/salas_/$salaId'
      path: '/salas/$salaId'
      fullPath: '/salas/$salaId'
      preLoaderRoute: typeof SalasSalaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/painel': {
      id: '/gestao_/painel'
      path: '/gestao/painel'
      fullPath: '/gestao/painel'
      preLoaderRoute: typeof GestaoPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestaoRoute: GestaoRoute,
  SalasRoute: SalasRoute,
  GestaoPainelRoute: GestaoPainelRoute,
  SalasSalaIdRoute: SalasSalaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
